version: 2.4.4.1

branches:
  only:
  - master

image: Visual Studio 2017

configuration: 
  - Release

platform:
- x86

before_build:
- cmd: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    appveyor-retry nuget restore

build:
  publish_nuget: true
  verbosity: minimal
  parallel: true

test:
  assemblies:
    only:
    - ./BassVisAPI.Net.Tests/bin/x86/Release/net45/BassVisAPI.Net.Tests.dll

artifacts:

- path: ./BassVisAPI.Net/bin/x86/Release/*.nupkg

  name: Nuget package